### ISSUE TITLE
Problem with the display in my work area

### ISSUE THREAD

**Issue by Monto753** [AuxilManagementGmbH/WasserfallExtended#2]
Hello, I have a problem with the display of the wasserfall auxiliary object, when I publish my Power BI file it does not let me see colors or the editing that I have previously done, here is an example:

<img width="242" alt="Example" src="https://github.com/user-attachments/assets/fae308aa-77ad-4607-b430-7064e3f24cb8">

Issue: 

<img width="239" alt="image" src="https://github.com/user-attachments/assets/aacf88c7-0482-4418-b533-6cec81277f07">

**Comment by lennartwollatz** [comment]
Hi, 
This issue appears, if the online version of the waterfall has a higher version as the visual on your lokal laptop (PowerBi Desktop) 

Since the interface has been changed by mid last week, there might be a difference between you desktop an online version. 

Please try to install the newest version at your PowerBi Desktop, by downloading it from the Marketplace. That should override the old version for sure. 

If that doesn’t help, please contact us again. 

Best regards, 
Auxil

**Comment by Monto753** [comment]
Hi, that was indeed the error, thank you very much for your help.

Best regards,
